const assert = require("node:assert/strict");
const fs = require("node:fs");
const http = require("node:http");
const { chromium } = require("playwright");

(async () => {
  const browser = await chromium.launch({ headless:true, executablePath:"/usr/bin/chromium", args:["--no-sandbox"] });
  const sandboxPage = await browser.newPage({ viewport:{ width:390, height:844 } });
  await sandboxPage.setContent('<iframe sandbox="allow-scripts" style="width:390px;height:844px"></iframe>');
  await sandboxPage.locator("iframe").evaluate((frame,source) => { frame.srcdoc=source; }, fs.readFileSync("Service-Ecology-DEMO-0.3.0.html", "utf8"));
  const sandboxFrame = sandboxPage.frames()[1];
  await sandboxFrame.waitForSelector("#login-form");
  assert.equal(await sandboxFrame.locator("#login-form input").count(), 2);
  await sandboxFrame.getByPlaceholder("Логин").fill("master");
  await sandboxFrame.getByPlaceholder("Пароль").fill("MasterDemo123!");
  await sandboxFrame.getByRole("button", { name:"Войти" }).click();
  await sandboxFrame.locator(".topbar").waitFor();
  await sandboxPage.close();
  const server = http.createServer((_, response) => { response.setHeader("Content-Type", "text/html; charset=utf-8"); response.end(fs.readFileSync("Service-Ecology-DEMO-0.3.0.html")); });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const page = await browser.newPage({ viewport:{ width:390, height:844 } });
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  assert.equal(await page.locator("#login-form input").count(), 2);
  await page.getByPlaceholder("Логин").fill("master");
  await page.getByPlaceholder("Пароль").fill("MasterDemo123!");
  await page.getByRole("button", { name:"Войти" }).click();
  assert.equal(await page.locator('#entry-form input[type="file"]').count(), 5);
  await page.getByRole("button", { name:"Приёмка ТБО" }).click();
  assert.equal(await page.locator('#entry-form input[type="file"]').count(), 5);
  await page.getByRole("button", { name:"Мои записи" }).click();
  assert.equal(await page.locator(".calendar-grid").count(), 1);
  await page.getByRole("button", { name:"Суточный отчёт" }).click();
  assert.equal(await page.locator('#daily-form input[type="file"]').count(), 6);
  await page.locator("#landfill").fill("Тестовый полигон");
  const pixel = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");
  for (const input of await page.locator('#daily-form input[type="file"]').all()) await input.setInputFiles({ name:"photo.png", mimeType:"image/png", buffer:pixel });
  await page.getByRole("button", { name:"Отправить отчёт" }).click();
  await page.getByRole("button", { name:"Выйти" }).click();
  await page.getByPlaceholder("Логин").fill("itr");
  await page.getByPlaceholder("Пароль").fill("ItrDemo123!");
  await page.getByRole("button", { name:"Войти" }).click();
  await page.getByRole("button", { name:"Отчёты мастеров" }).click();
  await page.getByText("Тестовый полигон").first().waitFor();
  assert.equal(await page.locator(".badge").count(), 6);
  await browser.close();
  server.close();
  console.log("browser: ok");
})().catch((error) => { console.error(error); process.exit(1); });
