(function () {
  "use strict";
  const app = document.getElementById("app");
  const DB_NAME = "eco-mvp-v030";
  const USERS = { master:{password:"MasterDemo123!",role:"master",name:"Мастер"}, itr:{password:"ItrDemo123!",role:"itr",name:"ИТР"} };
  const memory = {};
  function storage(kind) { try { const value=window[kind]; value.getItem("eco-access-test"); return value; } catch (_) { return null; } }
  const localStore=storage("localStorage"), sessionStore=storage("sessionStorage");
  const getValue=(store,name)=>store?store.getItem(name):(name in memory?memory[name]:null);
  const setValue=(store,name,value)=>{if(store)store.setItem(name,value);else memory[name]=String(value);};
  const removeValue=(store,name)=>{if(store)store.removeItem(name);else delete memory[name];};
  let session = JSON.parse(getValue(sessionStore,"eco-session") || "null");
  let active = "";
  const uid = () => (crypto.randomUUID ? crypto.randomUUID() : Date.now()+"-"+Math.random()).toString();
  const key = (name) => DB_NAME + ":" + name;
  const read = (name) => { try { return JSON.parse(getValue(localStore,key(name)) || "[]"); } catch (_) { return []; } };
  const write = (name,value) => setValue(localStore,key(name),JSON.stringify(value));
  const draftKey = () => key("daily-draft:" + session.login);
  function toast(message){const node=document.getElementById("toast");node.textContent=message;node.classList.add("show");setTimeout(()=>node.classList.remove("show"),1800);}
  function photoPayload(file) {
    if (!window.ECO_CONFIG.apiUrl) return Promise.resolve({name:file.name,size:file.size,type:file.type});
    return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error("Не удалось прочитать фото"));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error("Не удалось обработать фото"));image.onload=()=>{const limit=1600,scale=Math.min(1,limit/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);const data=canvas.toDataURL("image/jpeg",.78);resolve({name:file.name,size:data.length,type:"image/jpeg",data});};image.src=reader.result;};reader.readAsDataURL(file);});
  }

  async function api(action,payload={}) {
    if (!window.ECO_CONFIG.apiUrl) return demoApi(action,payload);
    const response=await fetch(window.ECO_CONFIG.apiUrl,{method:"POST",body:JSON.stringify({action,sessionToken:session&&session.token,payload})});
    const result=await response.json(); if(!result.ok) throw new Error(result.error||"Ошибка сервера"); return result.data;
  }
  function demoApi(action,payload) {
    if(action==="login"){const user=USERS[payload.login];if(!user||user.password!==payload.password)throw new Error("Неверный логин или пароль");return{token:uid(),login:payload.login,role:user.role,name:user.name};}
    if(!session)throw new Error("Требуется вход");
    if(action==="listEntries")return read("entries").filter((x)=>session.role==="itr"||x.author===session.login);
    if(action==="saveEntry"){const all=read("entries"),found=all.find((x)=>x.requestId===payload.requestId);if(found)return found;payload.id=uid();payload.author=session.login;payload.createdAt=new Date().toISOString();payload.confirmed=false;all.unshift(payload);write("entries",all);return payload;}
    if(action==="confirmEntry"){if(session.role!=="itr")throw new Error("Недостаточно прав");const all=read("entries"),item=all.find((x)=>x.id===payload.id);if(!item)throw new Error("Запись не найдена");item.confirmed=true;item.confirmedAt=new Date().toISOString();write("entries",all);return item;}
    if(action==="saveDaily"){if(session.role!=="master")throw new Error("Недостаточно прав");const errors=EcoReportModel.validate(payload);if(errors.length)throw new Error(errors.join("\n"));const all=read("daily"),found=all.find((x)=>x.requestId===payload.requestId);if(found)return found;payload.id=uid();payload.author=session.login;payload.createdAt=new Date().toISOString();all.unshift(payload);write("daily",all);return payload;}
    if(action==="listDaily")return read("daily").filter((x)=>session.role==="itr"||x.author===session.login);
    throw new Error("Неизвестное действие");
  }
  function loginView(){app.innerHTML='<section class="login"><form id="login-form"><input name="login" aria-label="Логин" autocomplete="username" placeholder="Логин" required><input name="password" aria-label="Пароль" type="password" autocomplete="current-password" placeholder="Пароль" required><button class="primary" id="login-button" type="button">Войти</button><div id="login-error" class="error"></div></form></section>';const form=document.getElementById("login-form"),login=async()=>{const loginValue=form.elements.login.value.trim().toLowerCase(),password=form.elements.password.value.trim();if(!loginValue||!password){document.getElementById("login-error").textContent="Введите логин и пароль";return;}try{session=await api("login",{login:loginValue,password});setValue(sessionStore,"eco-session",JSON.stringify(session));renderShell();}catch(error){document.getElementById("login-error").textContent=error.message;}};document.getElementById("login-button").onclick=login;form.addEventListener("keydown",(event)=>{if(event.key==="Enter"){event.preventDefault();login();}});}
  const tabs=()=>session.role==="master"?[["nso","Приёмка НСО"],["tbo","Приёмка ТБО"],["journal","Мои записи"],["daily","Суточный отчёт"]]:[["journal","Общий журнал"],["summary","Отчёт 14 дней"],["daily-list","Отчёты мастеров"]];
  function renderShell(){active=active||tabs()[0][0];app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark" aria-hidden="true">↻</span><span><strong>Сервис Экология</strong><small>Учёт приёмки</small></span></div><button id="logout">Выйти</button></header><nav class="tabs">${tabs().map(([id,label])=>`<button data-tab="${id}" class="${active===id?"active":""}">${label}</button>`).join("")}</nav><div class="statusbar"><span>Рабочее место ${session.role==="master"?"мастера":"ИТР"}</span><span class="online"><i></i> На связи</span></div><div id="content"></div></div>`;document.getElementById("logout").onclick=()=>{session=null;active="";removeValue(sessionStore,"eco-session");loginView();};document.querySelectorAll("[data-tab]").forEach((button)=>button.onclick=()=>{active=button.dataset.tab;renderShell();});renderContent();}
  function statsMarkup(){return `<div class="stats"><div class="stat"><small>Принято сегодня</small><strong id="stat-today">0</strong></div><div class="stat"><small>Принято НСО сегодня</small><strong id="stat-nso">0 т</strong></div><div class="stat"><small>Принято ТБО сегодня</small><strong id="stat-tbo">0 т</strong></div></div>`;}
  function receptionForm(type){const nso=type==="NSO",photoLabels=nso?["Машина и номер","Показания весов","ТТН"]:["Мусоровоз"];return `<main class="workspace"><div class="page-heading"><span class="eyebrow">Приёмка отходов</span><h1>Приёмка ${type}</h1><p>Зафиксируйте вес и приложите фотофиксацию.</p></div>${statsMarkup()}<section class="card form-card"><form id="entry-form"><input type="hidden" name="type" value="${type}"><input type="hidden" name="requestId" value="${uid()}"><fieldset><legend><span>1</span> Данные приёмки</legend><div class="grid"><div class="field"><label>${nso?"Номер машины":"Номер мусоровоза"}</label><input name="vehicle" placeholder="A123BC 163" required></div><div class="field"><label>Масса, т</label><input name="mass" placeholder="0,000" type="number" min="0.001" step="0.001" inputmode="decimal" required></div>${nso?'<div class="field full"><label>Номер ТТН</label><input name="ttn" placeholder="Номер накладной" required></div>':""}</div></fieldset><fieldset><legend><span>2</span> Фотофиксация <em>0 / ${nso?3:1}</em></legend><div class="photo-grid">${photoLabels.map((label,i)=>`<label class="photo"><input name="photo${i+1}" type="file" accept="image/*" capture="environment" required><b>＋</b><strong>${label}</strong><small>Снять или выбрать</small></label>`).join("")}</div></fieldset><p class="form-note">После отправки запись поступит на проверку ИТР.</p><button class="primary submit-wide" type="submit">Отправить на проверку</button><div id="entry-error" class="error"></div></form></section></main>`;}
  async function updateStats(){const rows=await api("listEntries"),today=new Date().toISOString().slice(0,10),current=rows.filter((x)=>String(x.createdAt).slice(0,10)===today),sum=(type)=>current.filter((x)=>x.type===type).reduce((total,x)=>total+Number(x.mass),0);const values={"stat-today":current.length,"stat-nso":sum("NSO").toFixed(3)+" т","stat-tbo":sum("TBO").toFixed(3)+" т"};Object.entries(values).forEach(([id,value])=>{const node=document.getElementById(id);if(node)node.textContent=value;});}
  function bindReception(){const form=document.getElementById("entry-form"),files=[...form.querySelectorAll('input[type="file"]')],counter=form.querySelector("fieldset:nth-of-type(2) legend em"),refreshPhotos=()=>{const count=files.filter((input)=>input.files.length).length;counter.textContent=count+" / "+files.length;files.forEach((input)=>input.closest(".photo").classList.toggle("selected",!!input.files.length));};files.forEach((input)=>input.onchange=refreshPhotos);form.onsubmit=async(event)=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));data.mass=EcoReportModel.number(data.mass);data.photos=[];try{for(const input of files){const file=input.files[0];if(file)data.photos.push(await photoPayload(file));delete data[input.name];}await api("saveEntry",data);toast("Запись сохранена");form.reset();form.requestId.value=uid();refreshPhotos();updateStats();}catch(error){document.getElementById("entry-error").textContent=error.message;}};}
  async function journalView(){const rows=await api("listEntries");document.getElementById("content").innerHTML=`<main class="workspace"><div class="page-heading split"><div><span class="eyebrow">Личный журнал</span><h1>${session.role==="itr"?"Общий журнал":"Мои записи"}</h1><p>${session.role==="itr"?"Все записи мастеров НСО и ТБО.":"Все ваши приёмки НСО и ТБО."}</p></div><button class="secondary" id="refresh">Обновить</button></div>${statsMarkup()}<section class="filters"><select id="period"><option>За всё время</option><option>Сегодня</option><option>За 7 дней</option><option>За 30 дней</option></select><select id="entry-type"><option value="">НСО и ТБО</option><option value="NSO">Только НСО</option><option value="TBO">Только ТБО</option></select><input id="entry-search" placeholder="Машина, мастер или ТТН"></section><section class="card"><div class="list" id="entry-list">${rows.length?rows.map((x)=>`<article class="item" data-type="${x.type}" data-search="${EcoReports.esc((x.vehicle+" "+x.author+" "+(x.ttn||"")).toLowerCase())}"><div class="item-head"><strong>${x.type} · ${EcoReports.esc(x.vehicle)}</strong><span class="badge ${x.confirmed?"ok":""}">${x.confirmed?"Подтверждено":"Ожидает"}</span></div><div>${x.mass} т · ${new Date(x.createdAt).toLocaleString("ru-RU")}</div>${session.role==="itr"&&!x.confirmed?`<div class="actions"><button class="secondary" data-confirm="${x.id}">Подтвердить</button></div>`:""}</article>`).join(""):'<div class="empty"><b>Записей пока нет</b><small>Здесь появятся приёмки, подходящие под выбранные фильтры.</small></div>'}</div></section></main>`;await updateStats();document.getElementById("refresh").onclick=journalView;const filter=()=>{const type=document.getElementById("entry-type").value,query=document.getElementById("entry-search").value.toLowerCase();document.querySelectorAll("#entry-list .item").forEach((item)=>item.hidden=(!!type&&item.dataset.type!==type)||!item.dataset.search.includes(query));};document.getElementById("entry-type").onchange=filter;document.getElementById("entry-search").oninput=filter;document.querySelectorAll("[data-confirm]").forEach((button)=>button.onclick=async()=>{await api("confirmEntry",{id:button.dataset.confirm});toast("Запись подтверждена");journalView();});}
  async function summaryView(){const since=Date.now()-14*86400000,rows=(await api("listEntries")).filter((x)=>new Date(x.createdAt).getTime()>=since),totals=rows.reduce((a,x)=>(a[x.type]=(a[x.type]||0)+Number(x.mass),a),{});document.getElementById("content").innerHTML=`<main class="workspace"><div class="page-heading"><span class="eyebrow">Аналитика</span><h1>Сводка за 14 дней</h1><p>Подтверждённые и ожидающие записи по всем видам отходов.</p></div><div class="stats"><div class="stat"><small>Всего записей</small><strong>${rows.length}</strong></div><div class="stat"><small>Принято НСО</small><strong>${(totals.NSO||0).toFixed(3)} т</strong></div><div class="stat"><small>Принято ТБО</small><strong>${(totals.TBO||0).toFixed(3)} т</strong></div></div><section class="card padded"><div class="actions"><button id="csv" class="primary">Скачать CSV для Excel</button></div></section></main>`;document.getElementById("csv").onclick=()=>{const csv="Тип;ТС;Масса, т;Дата;Статус\n"+rows.map((x)=>[x.type,x.vehicle,x.mass,x.createdAt,x.confirmed?"Подтверждено":"Ожидает"].join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));a.download="ecology-14-days.csv";a.click();URL.revokeObjectURL(a.href);};}
  function bindDaily(){const form=document.getElementById("daily-form"),preview=document.getElementById("daily-preview"),saved=JSON.parse(getValue(localStore,draftKey())||"{}"),saveDraft=()=>{const report=update();setValue(localStore,draftKey(),JSON.stringify(report));};let timer;const update=()=>{const report=EcoReports.collect(form,saved.photos);preview.textContent=EcoReportModel.format(report);return report;};form.addEventListener("input",()=>{update();clearTimeout(timer);timer=setTimeout(saveDraft,500);});document.getElementById("save-draft").onclick=()=>{saveDraft();toast("Черновик сохранён");};form.onsubmit=async(event)=>{event.preventDefault();const report=update();report.requestId=uid();try{for(const [field] of EcoReportModel.PHOTO_FIELDS){const file=form.elements["photo-"+field].files[0];if(file)report.photos[field]=await photoPayload(file);}const errors=EcoReportModel.validate(report);if(errors.length){document.getElementById("daily-error").textContent=errors.join("\n");return;}await api("saveDaily",report);removeValue(localStore,draftKey());toast("Отчёт отправлен");active="journal";renderShell();}catch(error){document.getElementById("daily-error").textContent=error.message;}};}
  async function dailyListView(){const reports=await api("listDaily");document.getElementById("content").innerHTML=`<main class="workspace"><div class="page-heading"><span class="eyebrow">Суточная сводка</span><h1>Отчёты мастеров</h1><p>Показатели смен, комментарии и фотофиксация.</p></div><section class="card"><div class="list">${reports.length?reports.map((x)=>`<details class="item"><summary><strong>${x.date} · ${EcoReports.esc(x.landfill)}</strong> · ${EcoReports.esc(x.author)}</summary><div class="preview">${EcoReports.esc(EcoReportModel.format(x))}</div><div>${EcoReportModel.PHOTO_FIELDS.map(([k,l])=>`<span class="badge">${l}: ${EcoReports.esc(x.photos[k].name)}</span>`).join(" ")}</div></details>`).join(""):'<div class="empty"><b>Отчётов пока нет</b><small>Отправленные мастерами отчёты появятся здесь.</small></div>'}</div></section></main>`;}
  async function renderContent(){const content=document.getElementById("content");try{if(active==="nso"||active==="tbo"){content.innerHTML=receptionForm(active.toUpperCase());bindReception();updateStats();}else if(active==="journal")await journalView();else if(active==="summary")await summaryView();else if(active==="daily"){const draft=JSON.parse(getValue(localStore,draftKey())||"{}");content.innerHTML=EcoReports.dailyForm(draft);bindDaily();}else if(active==="daily-list")await dailyListView();}catch(error){content.innerHTML=`<section class="card error">${EcoReports.esc(error.message)}</section>`;}}
  if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("service-worker.js").catch(()=>{});
  session?renderShell():loginView();
})();
